In [30]:
import numpy as np

# 1.Create a null vector of size 10 but the fifth value which is 1.

In [31]:
x=np.zeros(10)
x[4]=1
x

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

# 2.Create a vector with values ranging from 10 to 49.

In [32]:
vet=np.arange(10,50)
vet

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

# 3.Create a 3x3 matrix with values ranging from 0 to 8

In [33]:
mat=np.arange(0,9).reshape(3,3)
mat

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# 4.Find indices of non-zero elements from [1,2,0,0,4,0]

In [34]:
nonzeroele=np.nonzero([1,2,0,0,4,0])
nonzeroele

(array([0, 1, 4], dtype=int64),)

# 5.Create a 10x10 array with random values and find the minimum and maximum values.

In [35]:
mata=np.random.random((10,10))
mata

array([[0.31052301, 0.44793919, 0.85532661, 0.24792043, 0.66284129,
        0.44808445, 0.61861447, 0.95133136, 0.93304526, 0.99703565],
       [0.6326298 , 0.6958972 , 0.77242951, 0.10387965, 0.19531046,
        0.31083268, 0.53561568, 0.83639721, 0.17628462, 0.34576359],
       [0.98675294, 0.33261827, 0.10234122, 0.09413401, 0.43632054,
        0.87958779, 0.40563358, 0.82527164, 0.87332226, 0.86253694],
       [0.74310523, 0.59740808, 0.11684558, 0.80416594, 0.27745837,
        0.84249868, 0.09047582, 0.40525082, 0.97167745, 0.26463663],
       [0.97925733, 0.66668301, 0.37407432, 0.77353315, 0.71123041,
        0.01829518, 0.90961481, 0.63238955, 0.10821831, 0.81408005],
       [0.1546963 , 0.31211209, 0.03989123, 0.44673493, 0.29013522,
        0.08325148, 0.18358547, 0.74642375, 0.98532771, 0.96047061],
       [0.09338061, 0.88083311, 0.41209573, 0.49044383, 0.29552091,
        0.71667155, 0.18579535, 0.81646595, 0.14848785, 0.30115686],
       [0.99513461, 0.75929345, 0.2688571

In [36]:
mata_min=mata.min()
mata_max=mata.max()

In [37]:
print(mata_min,mata_max)

0.01829517812463244 0.9970356549448889


# 6.Create a 10x10 array with random values and find the minimum and maximum values

In [38]:
mat=np.random.random(30)
mean=mat.mean()
mean

0.44867586005147164